[package]
name = "leptos-events-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = "0.2.1"
tracing = "0.1.37"
tracing-wasm = "0.2.1"
